# Generated by Django 4.2.2 on 2023-06-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='venue_image',
        ),
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
