# Generated by Django 4.2.2 on 2023-06-15 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_attendees_alter_event_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='address',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='web',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='zip_code',
        ),
    ]
