# Generated by Django 4.2.2 on 2023-06-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_attendees_applyevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(verbose_name='Event Date'),
        ),
    ]
